version: "3.8"

services:
  rabbit:
    image: rabbitmq:4-management
    container_name: rabbit
    hostname: rabbit-serv
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
    volumes:
      - rabbit-data:/var/lib/rabbitmq

volumes:
  rabbit-data:
