version: "3.8"

services:
  rabbit:
    image: rabbitmq:4-management
    container_name: rabbit
    hostname: rabbit-serv
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json
    volumes:
      - rabbit-data:/var/lib/rabbitmq
      - ./rabbitmq-conf.json:/etc/rabbitmq/definitions.json

volumes:
  rabbit-data:
